# docker compose up -d --build --force-recreate
# docker compose down
version: '3.4'

services:
  ml-inference-api:
    image: tosharathshetty/ml-inference
    build:
      context: ./ml-train-test-inference/api
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    healthcheck:
      test: curl --fail http://localhost:8080 || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
    volumes:
      - ./ml-train-test-inference/api:/data

  ml-ui:
    image: tosharathshetty/ml-ui
    build:
      context: ./ml-ui
      dockerfile: Dockerfile
    ports:
      - 7860:7860
    healthcheck:
      test: curl --fail http://localhost:7860 || exit 1
      interval: 60s
      retries: 5
      start_period: 10s
      timeout: 10s
    volumes:
      - ./ml-ui:/data

    depends_on:
      ml-inference-api:
        condition: service_healthy